### ISSUE TITLE
Issue building on Ubuntu 19.04

### ISSUE THREAD

**Issue by jakew009** [fac/auth-script-openvpn#15]
Hey

Thanks so much for creating and releasing this!

I had an issue building it on Ubuntu 19.04 with OpenVPN so I thought I would share them here in case anyone else had the same troubles

When I called `make plugin`, I was getting an error that openvpn-plugin.h could not be found.
On some further investigation, I found that by changing line 21 from:

`#include <openvpn-plugin.h>`
to:
`#include <openvpn/openvpn-plugin.h>`

It was able to build and work perfectly.

My linux knowledge is fairly limited so I don't know what a proper fix for this would be :)

**Comment by wbwork** [comment]
Applies also for Ubuntu 18.04 already.
