### ISSUE TITLE
Auth hangs if script fails to exec

### ISSUE THREAD

**Issue by caius** [fac/auth-script-openvpn#2]
1. Configure the plugin to call a script that doesn't exist
2. `execve` call will fail and log it's failure to exec
3. Currently openvpn will keep the auth pending until the timeout for deferred authentication is triggered, at which point the auth will fail.

We know the authentication can't succeed once the exec fails, it would be nice if the plugin error handler for `execve` wrote an auth failure to the `auth_control_file` so we failed quicker.

**Comment by g00nix** [comment]
It also randomly happens that the auth can not exec the script, so the login will hang at:
```
Mon Oct 14 19:38:38 2019 us=424660 81.180.227.170:47634 PUSH: Received control message: 'PUSH_REQUEST'
Mon Oct 14 19:38:43 2019 us=563493 81.180.227.170:47634 PUSH: Received control message: 'PUSH_REQUEST'
Mon Oct 14 19:38:48 2019 us=700823 81.180.227.170:47634 PUSH: Received control message: 'PUSH_REQUEST'
Mon Oct 14 19:38:53 2019 us=730106 81.180.227.170:47634 PUSH: Received control message: 'PUSH_REQUEST'
```
