### ISSUE TITLE
EFAULT when running php script

### ISSUE THREAD

**Issue by fliespl** [fac/auth-script-openvpn#22]
Php with proper shebang fails with EFAULT.

Once I add another .sh wrapper and run php from it - it works.

Any ideas?

**Comment by dselyuzhitskiy** [comment]
Possibly same problem with go binary
`
[pid  5087] execve("/root/main", ["/root/main", 0x656e6e6f632d0000, 0x31, 0x800000000001, "md4WithRSAEncryption", "MD4", 0x3d4449504e49414d, 0x30, 0x21], 0x55ecbf850428 /* 47 vars */) = -1 EFAULT (Bad address)`
