### ISSUE TITLE
push "auth-token" - not working

### ISSUE THREAD

**Issue by fliespl** [fac/auth-script-openvpn#23]
My script gets called on every renegotiation, but no matter if I write to auth_control_file or allow / fail with exit code - session would still expire.

I don't think it handles tokens properly.

**Comment by abaddononion** [comment]
Yeah I'd like to upvote this issue... having auth-token work with this script would greatly improve its usability for us. When every reconnect means a full username/password/MFA again, there are limited pleasant ways you can configure your VPN. Either you have to turn reneg-sec up so high that you reduce security, or you drive users crazy with constant full reauthentications. I'm not sure exactly what it would take to make the plugin support auth-token, or if it's even possible... but it would definitely be a big improvement for us (or you know... openvpn could just stop being single-threaded. that'd be nice too).
